# analysis method prefs for preferentially parsing oreas catalogue.
# last updated ZH 20231012

# all assay methods as of 20231012:
#  '4-Acid Digestion'
#  '3-Acid Digestion (no HF)'
#  'Acid Digestion (no HF)'
#  'Pb Fire Assay'
#  'NiS Fire Assay'
#  'Pb Fire Assay (Grav)'
#  'Pb/NiS Fire Assay'
#  'Pb Fire Assay (full corrections)'
#  'Borate Fusion XRF'
#  'Oxidising Fusion XRF'
#  'Pressed Powder Pellet XRF'
#  'Borate / Peroxide Fusion ICP'
#  'Peroxide Fusion ICP'
#  'Aqua Regia Digestion'
#  'Aqua Regia Digestion (sample weights 0.15-50g)'
#  'Aqua Regia Digestion (sample weights 10-50g)'
#  'Infrared Combustion'
#  'Thermogravimetry'
#  'Cyanide Leach'
#  'Gas / Liquid Pycnometry'
# 'Sulphuric Acid 5% Leach'
#  'PhotonAssay'
#  'Classical Wet Chemistry'
#  'Sulphuric Acid 10% Leach'
#  'Acid Digestion Titration'
#  'Satmagan 135'
#  'Davis Tube Recovery'
#  'Miscellaneous Assay Methods'


# set up dict of preferred analysis methods for each element - format: (key)*Element*: (value)[*1st pref*, *2nd pref*, *3rd pref*,...]
analysis_method_prefs_dict = {
    'Ag': [ 'Pb Fire Assay',
            'NiS Fire Assay',
            'Pb Fire Assay (Grav)',
            'Pb/NiS Fire Assay',
            'Pb Fire Assay (full corrections)',
            'Aqua Regia Digestion',
            'Aqua Regia Digestion (sample weights 0.15-50g)',
            'Aqua Regia Digestion (sample weights 10-50g)',
            'Borate / Peroxide Fusion ICP',
            'Peroxide Fusion ICP',
            '4-Acid Digestion',
            '3-Acid Digestion (no HF)',
            'Acid Digestion (no HF)'],

    'Al': [ '4-Acid Digestion',
            '3-Acid Digestion (no HF)',
            'Acid Digestion (no HF)',
            'Borate Fusion XRF',
            'Oxidising Fusion XRF',
            'Pressed Powder Pellet XRF',
            'Borate / Peroxide Fusion ICP',
            'Peroxide Fusion ICP',
            'Aqua Regia Digestion',
            'Aqua Regia Digestion (sample weights 0.15-50g)',
            'Aqua Regia Digestion (sample weights 10-50g)'],

    'As': [ '4-Acid Digestion',
            '3-Acid Digestion (no HF)',
            'Acid Digestion (no HF)',
            'Borate Fusion XRF',
            'Oxidising Fusion XRF',
            'Pressed Powder Pellet XRF',
            'Borate / Peroxide Fusion ICP',
            'Peroxide Fusion ICP',
            'Aqua Regia Digestion',
            'Aqua Regia Digestion (sample weights 0.15-50g)',
            'Aqua Regia Digestion (sample weights 10-50g)'],
    
    'Au': [ 'Pb Fire Assay',
            'NiS Fire Assay',
            'Pb Fire Assay (Grav)',
            'Pb/NiS Fire Assay',
            'Pb Fire Assay (full corrections)',
            'Aqua Regia Digestion',
            'Aqua Regia Digestion (sample weights 0.15-50g)',
            'Aqua Regia Digestion (sample weights 10-50g)'],

    'B': [ 'Borate / Peroxide Fusion ICP',
            'Peroxide Fusion ICP',
            'Aqua Regia Digestion',
            'Aqua Regia Digestion (sample weights 0.15-50g)',
            'Aqua Regia Digestion (sample weights 10-50g)'],

    'Ba': [ '4-Acid Digestion',
            '3-Acid Digestion (no HF)',
            'Acid Digestion (no HF)',
            'Borate Fusion XRF',
            'Oxidising Fusion XRF',
            'Pressed Powder Pellet XRF',
            'Borate / Peroxide Fusion ICP',
            'Peroxide Fusion ICP',
            'Aqua Regia Digestion',
            'Aqua Regia Digestion (sample weights 0.15-50g)',
            'Aqua Regia Digestion (sample weights 10-50g)'],

    'Be': [ '4-Acid Digestion',
            '3-Acid Digestion (no HF)',
            'Acid Digestion (no HF)',
            'Borate / Peroxide Fusion ICP',
            'Peroxide Fusion ICP',
            'Aqua Regia Digestion',
            'Aqua Regia Digestion (sample weights 0.15-50g)',
            'Aqua Regia Digestion (sample weights 10-50g)'],
    
    'Bi': [ '4-Acid Digestion',
            '3-Acid Digestion (no HF)',
            'Acid Digestion (no HF)',
            'Borate / Peroxide Fusion ICP',
            'Peroxide Fusion ICP',
            'Aqua Regia Digestion',
            'Aqua Regia Digestion (sample weights 0.15-50g)',
            'Aqua Regia Digestion (sample weights 10-50g)'],
    
    'Ca': [ '4-Acid Digestion',
            '3-Acid Digestion (no HF)',
            'Acid Digestion (no HF)',
            'Borate Fusion XRF',
            'Oxidising Fusion XRF',
            'Pressed Powder Pellet XRF',
            'Borate / Peroxide Fusion ICP',
            'Peroxide Fusion ICP',
            'Aqua Regia Digestion',
            'Aqua Regia Digestion (sample weights 0.15-50g)',
            'Aqua Regia Digestion (sample weights 10-50g)'],

    'Cd': [ '4-Acid Digestion',
            '3-Acid Digestion (no HF)',
            'Acid Digestion (no HF)',
            'Borate / Peroxide Fusion ICP',
            'Peroxide Fusion ICP',
            'Aqua Regia Digestion',
            'Aqua Regia Digestion (sample weights 0.15-50g)',
            'Aqua Regia Digestion (sample weights 10-50g)'],
    
    'Ce': [ '4-Acid Digestion',
            '3-Acid Digestion (no HF)',
            'Acid Digestion (no HF)',
            'Borate Fusion XRF',
            'Oxidising Fusion XRF',
            'Pressed Powder Pellet XRF',
            'Borate / Peroxide Fusion ICP',
            'Peroxide Fusion ICP',
            'Aqua Regia Digestion',
            'Aqua Regia Digestion (sample weights 0.15-50g)',
            'Aqua Regia Digestion (sample weights 10-50g)'],

    'Cl': [ 'Borate Fusion XRF',
            'Oxidising Fusion XRF',
            'Pressed Powder Pellet XRF',
            'Borate / Peroxide Fusion ICP',
            'Peroxide Fusion ICP'],
    
    'Co': [ '4-Acid Digestion',
            '3-Acid Digestion (no HF)',
            'Acid Digestion (no HF)',
            'Borate Fusion XRF',
            'Oxidising Fusion XRF'
            'Pressed Powder Pellet XRF',
            'Borate / Peroxide Fusion ICP',
            'Peroxide Fusion ICP'],

    'Cr': [ '4-Acid Digestion',
            '3-Acid Digestion (no HF)',
            'Acid Digestion (no HF)',
            'Borate Fusion XRF',
            'Oxidising Fusion XRF',
            'Pressed Powder Pellet XRF',
            'Borate / Peroxide Fusion ICP',
            'Peroxide Fusion ICP',
            'Aqua Regia Digestion',
            'Aqua Regia Digestion (sample weights 0.15-50g)',
            'Aqua Regia Digestion (sample weights 10-50g)'],

    'Cs': [ '4-Acid Digestion',
            '3-Acid Digestion (no HF)',
            'Acid Digestion (no HF)',
            'Borate / Peroxide Fusion ICP',
            'Peroxide Fusion ICP',
            'Aqua Regia Digestion',
            'Aqua Regia Digestion (sample weights 0.15-50g)',
            'Aqua Regia Digestion (sample weights 10-50g)'],

    'Cu': [ '4-Acid Digestion',
            '3-Acid Digestion (no HF)',
            'Acid Digestion (no HF)',
            'Borate Fusion XRF',
            'Oxidising Fusion XRF',
            'Pressed Powder Pellet XRF',
            'Borate / Peroxide Fusion ICP',
            'Peroxide Fusion ICP',
            'Aqua Regia Digestion',
            'Aqua Regia Digestion (sample weights 0.15-50g)',
            'Aqua Regia Digestion (sample weights 10-50g)'],
    
    'Dy': [ '4-Acid Digestion',
            '3-Acid Digestion (no HF)',
            'Acid Digestion (no HF)',
            'Borate / Peroxide Fusion ICP',
            'Peroxide Fusion ICP',
            'Aqua Regia Digestion',
            'Aqua Regia Digestion (sample weights 0.15-50g)',
            'Aqua Regia Digestion (sample weights 10-50g)'],

    'Er': [ '4-Acid Digestion',
            '3-Acid Digestion (no HF)',
            'Acid Digestion (no HF)',
            'Borate / Peroxide Fusion ICP',
            'Peroxide Fusion ICP',
            'Aqua Regia Digestion',
            'Aqua Regia Digestion (sample weights 0.15-50g)',
            'Aqua Regia Digestion (sample weights 10-50g)'],

    'Eu': [ '4-Acid Digestion',
            '3-Acid Digestion (no HF)',
            'Acid Digestion (no HF)',
            'Borate / Peroxide Fusion ICP',
            'Peroxide Fusion ICP',
            'Aqua Regia Digestion',
            'Aqua Regia Digestion (sample weights 0.15-50g)',
            'Aqua Regia Digestion (sample weights 10-50g)'],

    'Fe': [ '4-Acid Digestion',
            '3-Acid Digestion (no HF)',
            'Acid Digestion (no HF)',
            'Borate Fusion XRF',
            'Oxidising Fusion XRF',
            'Pressed Powder Pellet XRF',
            'Borate / Peroxide Fusion ICP',
            'Peroxide Fusion ICP',
            'Aqua Regia Digestion',
            'Aqua Regia Digestion (sample weights 0.15-50g)',
            'Aqua Regia Digestion (sample weights 10-50g)'],

    'Ga': [ '4-Acid Digestion',
            '3-Acid Digestion (no HF)',
            'Acid Digestion (no HF)',
            'Peroxide Fusion ICP',
            'Borate / Peroxide Fusion ICP',
            'Aqua Regia Digestion',
            'Aqua Regia Digestion (sample weights 0.15-50g)',
            'Aqua Regia Digestion (sample weights 10-50g)'],

    'Gd': [ '4-Acid Digestion',
            '3-Acid Digestion (no HF)',
            'Acid Digestion (no HF)',
            'Peroxide Fusion ICP',
            'Borate / Peroxide Fusion ICP',
            'Aqua Regia Digestion',
            'Aqua Regia Digestion (sample weights 0.15-50g)',
            'Aqua Regia Digestion (sample weights 10-50g)'],

    'Ge': [ '4-Acid Digestion',
            '3-Acid Digestion (no HF)',
            'Acid Digestion (no HF)',
            'Peroxide Fusion ICP',
            'Borate / Peroxide Fusion ICP',
            'Aqua Regia Digestion',
            'Aqua Regia Digestion (sample weights 0.15-50g)',
            'Aqua Regia Digestion (sample weights 10-50g)'],

    'Hf': [ '4-Acid Digestion',
            '3-Acid Digestion (no HF)',
            'Acid Digestion (no HF)',
            'Peroxide Fusion ICP',
            'Borate / Peroxide Fusion ICP',
            'Aqua Regia Digestion',
            'Aqua Regia Digestion (sample weights 0.15-50g)',
            'Aqua Regia Digestion (sample weights 10-50g)'],

    'Hg': [ '4-Acid Digestion',
            '3-Acid Digestion (no HF)',
            'Acid Digestion (no HF)',
            'Aqua Regia Digestion',
            'Aqua Regia Digestion (sample weights 0.15-50g)',
            'Aqua Regia Digestion (sample weights 10-50g)'],

    'Ho': [ '4-Acid Digestion',
            '3-Acid Digestion (no HF)',
            'Acid Digestion (no HF)',
            'Peroxide Fusion ICP',
            'Borate / Peroxide Fusion ICP',
            'Aqua Regia Digestion',
            'Aqua Regia Digestion (sample weights 0.15-50g)',
            'Aqua Regia Digestion (sample weights 10-50g)'],

    'In': [ '4-Acid Digestion',
            '3-Acid Digestion (no HF)',
            'Acid Digestion (no HF)',
            'Peroxide Fusion ICP',
            'Borate / Peroxide Fusion ICP',
            'Aqua Regia Digestion',
            'Aqua Regia Digestion (sample weights 0.15-50g)',
            'Aqua Regia Digestion (sample weights 10-50g)'],

    'Ir': [ 'Pb Fire Assay',
            'NiS Fire Assay',
            'Pb Fire Assay (Grav)',
            'Pb/NiS Fire Assay',
            'Pb Fire Assay (full corrections)',
            'Aqua Regia Digestion',
            'Aqua Regia Digestion (sample weights 0.15-50g)',
            'Aqua Regia Digestion (sample weights 10-50g)'],

    'K': [ '4-Acid Digestion',
            '3-Acid Digestion (no HF)',
            'Acid Digestion (no HF)',
            'Borate / Peroxide Fusion ICP',
            'Borate Fusion XRF',
            'Oxidising Fusion XRF',
            'Pressed Powder Pellet XRF',
            'Peroxide Fusion ICP',
            'Aqua Regia Digestion',
            'Aqua Regia Digestion (sample weights 0.15-50g)',
            'Aqua Regia Digestion (sample weights 10-50g)'],

    'La': [ '4-Acid Digestion',
            '3-Acid Digestion (no HF)',
            'Acid Digestion (no HF)',
            'Borate / Peroxide Fusion ICP',
            'Borate Fusion XRF',
            'Oxidising Fusion XRF',
            'Pressed Powder Pellet XRF',
            'Peroxide Fusion ICP',
            'Aqua Regia Digestion',
            'Aqua Regia Digestion (sample weights 0.15-50g)',
            'Aqua Regia Digestion (sample weights 10-50g)'],

    'Li': [ '4-Acid Digestion',
            '3-Acid Digestion (no HF)',
            'Acid Digestion (no HF)',
            'Peroxide Fusion ICP',
            'Borate / Peroxide Fusion ICP',
            'Aqua Regia Digestion',
            'Aqua Regia Digestion (sample weights 0.15-50g)',
            'Aqua Regia Digestion (sample weights 10-50g)'],

    'Lu': [ '4-Acid Digestion',
            '3-Acid Digestion (no HF)',
            'Acid Digestion (no HF)',
            'Peroxide Fusion ICP',
            'Borate / Peroxide Fusion ICP',
            'Aqua Regia Digestion',
            'Aqua Regia Digestion (sample weights 0.15-50g)',
            'Aqua Regia Digestion (sample weights 10-50g)'],

    'Mg': [ '4-Acid Digestion',
            '3-Acid Digestion (no HF)',
            'Acid Digestion (no HF)',
            'Borate / Peroxide Fusion ICP',
            'Borate Fusion XRF',
            'Oxidising Fusion XRF',
            'Pressed Powder Pellet XRF',
            'Peroxide Fusion ICP',
            'Aqua Regia Digestion',
            'Aqua Regia Digestion (sample weights 0.15-50g)',
            'Aqua Regia Digestion (sample weights 10-50g)'],

    'Mn': [ '4-Acid Digestion',
            '3-Acid Digestion (no HF)',
            'Acid Digestion (no HF)',
            'Borate / Peroxide Fusion ICP',
            'Borate Fusion XRF',
            'Oxidising Fusion XRF',
            'Pressed Powder Pellet XRF',
            'Peroxide Fusion ICP',
            'Aqua Regia Digestion',
            'Aqua Regia Digestion (sample weights 0.15-50g)',
            'Aqua Regia Digestion (sample weights 10-50g)'],

    'Mo': [ '4-Acid Digestion',
            '3-Acid Digestion (no HF)',
            'Acid Digestion (no HF)',
            'Peroxide Fusion ICP',
            'Borate / Peroxide Fusion ICP',
            'Aqua Regia Digestion',
            'Aqua Regia Digestion (sample weights 0.15-50g)',
            'Aqua Regia Digestion (sample weights 10-50g)'],

    'Na': [ '4-Acid Digestion',
            '3-Acid Digestion (no HF)',
            'Acid Digestion (no HF)',
            'Borate Fusion XRF',
            'Oxidising Fusion XRF',
            'Pressed Powder Pellet XRF',
            'Borate / Peroxide Fusion ICP',
            'Peroxide Fusion ICP',
            'Aqua Regia Digestion',
            'Aqua Regia Digestion (sample weights 0.15-50g)',
            'Aqua Regia Digestion (sample weights 10-50g)'],

    'Nb': [ '4-Acid Digestion',
            '3-Acid Digestion (no HF)',
            'Acid Digestion (no HF)',
            'Borate / Peroxide Fusion ICP',
            'Borate Fusion XRF',
            'Oxidising Fusion XRF',
            'Pressed Powder Pellet XRF',
            'Peroxide Fusion ICP',
            'Aqua Regia Digestion',
            'Aqua Regia Digestion (sample weights 0.15-50g)',
            'Aqua Regia Digestion (sample weights 10-50g)'],

    'Nd': ['4-Acid Digestion',
            '3-Acid Digestion (no HF)',
            'Acid Digestion (no HF)',
            'Borate Fusion XRF',
            'Oxidising Fusion XRF',
            'Pressed Powder Pellet XRF',
            'Borate / Peroxide Fusion ICP',
            'Peroxide Fusion ICP',
            'Aqua Regia Digestion',
            'Aqua Regia Digestion (sample weights 0.15-50g)',
            'Aqua Regia Digestion (sample weights 10-50g)'],

    'Ni': [ 'Borate Fusion XRF',
            'Oxidising Fusion XRF',
            'Pressed Powder Pellet XRF',
            'Borate / Peroxide Fusion ICP',
            'Peroxide Fusion ICP',
            'Aqua Regia Digestion',
            'Aqua Regia Digestion (sample weights 0.15-50g)',
            'Aqua Regia Digestion (sample weights 10-50g)'],

    'P': [ '4-Acid Digestion',
            '3-Acid Digestion (no HF)',
            'Acid Digestion (no HF)',
            'Borate Fusion XRF',
            'Oxidising Fusion XRF',
            'Pressed Powder Pellet XRF',
            'Borate / Peroxide Fusion ICP',
            'Peroxide Fusion ICP',
            'Aqua Regia Digestion',
            'Aqua Regia Digestion (sample weights 0.15-50g)',
            'Aqua Regia Digestion (sample weights 10-50g)'],

    'Pb': [ '4-Acid Digestion',
            '3-Acid Digestion (no HF)',
            'Acid Digestion (no HF)',
            'Borate Fusion XRF',
            'Oxidising Fusion XRF',
            'Pressed Powder Pellet XRF',
            'Borate / Peroxide Fusion ICP',
            'Peroxide Fusion ICP',
            'Aqua Regia Digestion',
            'Aqua Regia Digestion (sample weights 0.15-50g)',
            'Aqua Regia Digestion (sample weights 10-50g)'],

    'Pd': [ 'Pb Fire Assay',
            'NiS Fire Assay',
            'Pb Fire Assay (Grav)',
            'Pb/NiS Fire Assay',
            'Pb Fire Assay (full corrections)',
            'Aqua Regia Digestion',
            'Aqua Regia Digestion (sample weights 0.15-50g)',
            'Aqua Regia Digestion (sample weights 10-50g)'],

    'Pr': [ '4-Acid Digestion',
            '3-Acid Digestion (no HF)',
            'Acid Digestion (no HF)',
            'Borate Fusion XRF',
            'Oxidising Fusion XRF',
            'Pressed Powder Pellet XRF',
            'Borate / Peroxide Fusion ICP',
            'Peroxide Fusion ICP',
            'Aqua Regia Digestion',
            'Aqua Regia Digestion (sample weights 0.15-50g)',
            'Aqua Regia Digestion (sample weights 10-50g)'],

    'Pt': [ 'Pb Fire Assay',
            'NiS Fire Assay',
            'Pb Fire Assay (Grav)',
            'Pb/NiS Fire Assay',
            'Pb Fire Assay (full corrections)',
            'Aqua Regia Digestion',
            'Aqua Regia Digestion (sample weights 0.15-50g)',
            'Aqua Regia Digestion (sample weights 10-50g)'],

    'Rb': [ 'Borate / Peroxide Fusion ICP',
            'Peroxide Fusion ICP',
            'Aqua Regia Digestion',
            'Aqua Regia Digestion (sample weights 0.15-50g)',
            'Aqua Regia Digestion (sample weights 10-50g)'],
    
    'Re': [ 'Pb Fire Assay',
            'NiS Fire Assay',
            'Pb Fire Assay (Grav)',
            'Pb/NiS Fire Assay',
            'Pb Fire Assay (full corrections)',
            '4-Acid Digestion',
            '3-Acid Digestion (no HF)',
            'Acid Digestion (no HF)',
            'Aqua Regia Digestion',
            'Aqua Regia Digestion (sample weights 0.15-50g)',
            'Aqua Regia Digestion (sample weights 10-50g)'],

    'Rh': [ 'Pb Fire Assay',
            'NiS Fire Assay',
            'Pb Fire Assay (Grav)',
            'Pb/NiS Fire Assay',
            'Pb Fire Assay (full corrections)',
            'Aqua Regia Digestion',
            'Aqua Regia Digestion (sample weights 0.15-50g)',
            'Aqua Regia Digestion (sample weights 10-50g)'],

    'Ru': [ 'Pb Fire Assay',
            'NiS Fire Assay',
            'Pb Fire Assay (Grav)',
            'Pb/NiS Fire Assay',
            'Pb Fire Assay (full corrections)',
            'Aqua Regia Digestion',
            'Aqua Regia Digestion (sample weights 0.15-50g)',
            'Aqua Regia Digestion (sample weights 10-50g)'],

    'S': [ '4-Acid Digestion',
            '3-Acid Digestion (no HF)',
            'Acid Digestion (no HF)',
            'Borate Fusion XRF',
            'Oxidising Fusion XRF',
            'Pressed Powder Pellet XRF',
            'Borate / Peroxide Fusion ICP',
            'Peroxide Fusion ICP',
            'Aqua Regia Digestion',
            'Aqua Regia Digestion (sample weights 0.15-50g)',
            'Aqua Regia Digestion (sample weights 10-50g)'],

    'Sb': [ '4-Acid Digestion',
            '3-Acid Digestion (no HF)',
            'Acid Digestion (no HF)',
            'Borate / Peroxide Fusion ICP',
            'Peroxide Fusion ICP',
            'Aqua Regia Digestion',
            'Aqua Regia Digestion (sample weights 0.15-50g)',
            'Aqua Regia Digestion (sample weights 10-50g)'],

    'Sc': [ '4-Acid Digestion',
            '3-Acid Digestion (no HF)',
            'Acid Digestion (no HF)',
            'Borate Fusion XRF',
            'Oxidising Fusion XRF',
            'Pressed Powder Pellet XRF',
            'Borate / Peroxide Fusion ICP',
            'Peroxide Fusion ICP',
            'Aqua Regia Digestion',
            'Aqua Regia Digestion (sample weights 0.15-50g)',
            'Aqua Regia Digestion (sample weights 10-50g)'],

    'Se': [ '4-Acid Digestion',
            '3-Acid Digestion (no HF)',
            'Acid Digestion (no HF)',
            'Borate / Peroxide Fusion ICP',
            'Peroxide Fusion ICP',
            'Aqua Regia Digestion',
            'Aqua Regia Digestion (sample weights 0.15-50g)',
            'Aqua Regia Digestion (sample weights 10-50g)'],

    'Si': [ 'Borate Fusion XRF',
            'Oxidising Fusion XRF',
            'Pressed Powder Pellet XRF',
            'Borate / Peroxide Fusion ICP',
            'Peroxide Fusion ICP'],

    'Sm': [ 'Borate Fusion XRF',
            'Oxidising Fusion XRF',
            'Pressed Powder Pellet XRF',
            'Borate / Peroxide Fusion ICP',
            'Peroxide Fusion ICP',
            'Aqua Regia Digestion',
            'Aqua Regia Digestion (sample weights 0.15-50g)',
            'Aqua Regia Digestion (sample weights 10-50g)'],

    'Sn': [ '4-Acid Digestion',
            '3-Acid Digestion (no HF)',
            'Acid Digestion (no HF)',
            'Aqua Regia Digestion',
            'Aqua Regia Digestion (sample weights 0.15-50g)',
            'Aqua Regia Digestion (sample weights 10-50g)',
            'Borate / Peroxide Fusion ICP',
            'Borate Fusion XRF',
            'Oxidising Fusion XRF',
            'Pressed Powder Pellet XRF',
            'Peroxide Fusion ICP'],

    'Sr': [ '4-Acid Digestion',
            '3-Acid Digestion (no HF)',
            'Acid Digestion (no HF)',
            'Borate Fusion XRF',
            'Oxidising Fusion XRF',
            'Pressed Powder Pellet XRF',
            'Borate / Peroxide Fusion ICP',
            'Peroxide Fusion ICP',
            'Aqua Regia Digestion',
            'Aqua Regia Digestion (sample weights 0.15-50g)',
            'Aqua Regia Digestion (sample weights 10-50g)'],

    'Ta': [ '4-Acid Digestion',
            '3-Acid Digestion (no HF)',
            'Acid Digestion (no HF)',
            'Aqua Regia Digestion',
            'Aqua Regia Digestion (sample weights 0.15-50g)',
            'Aqua Regia Digestion (sample weights 10-50g)',
            'Borate / Peroxide Fusion ICP',
            'Peroxide Fusion ICP'],

    'Tb': [ '4-Acid Digestion',
            '3-Acid Digestion (no HF)',
            'Acid Digestion (no HF)',
            'Borate / Peroxide Fusion ICP',
            'Peroxide Fusion ICP',
            'Aqua Regia Digestion',
            'Aqua Regia Digestion (sample weights 0.15-50g)',
            'Aqua Regia Digestion (sample weights 10-50g)'],

    'Te': [ 'Peroxide Fusion ICP',
            'Borate / Peroxide Fusion ICP',
            'Aqua Regia Digestion',
            'Aqua Regia Digestion (sample weights 0.15-50g)',
            'Aqua Regia Digestion (sample weights 10-50g)'],

    'Th': [ '4-Acid Digestion',
            '3-Acid Digestion (no HF)',
            'Acid Digestion (no HF)',
            'Borate Fusion XRF',
            'Oxidising Fusion XRF',
            'Pressed Powder Pellet XRF',
            'Borate / Peroxide Fusion ICP',
            'Peroxide Fusion ICP',
            'Aqua Regia Digestion',
            'Aqua Regia Digestion (sample weights 0.15-50g)',
            'Aqua Regia Digestion (sample weights 10-50g)'],

    'Ti': [ '4-Acid Digestion',
            '3-Acid Digestion (no HF)',
            'Acid Digestion (no HF)',
            'Borate Fusion XRF',
            'Oxidising Fusion XRF',
            'Pressed Powder Pellet XRF',
            'Borate / Peroxide Fusion ICP',
            'Peroxide Fusion ICP',
            'Aqua Regia Digestion',
            'Aqua Regia Digestion (sample weights 0.15-50g)',
            'Aqua Regia Digestion (sample weights 10-50g)'],

    'Tl': [ '4-Acid Digestion',
            '3-Acid Digestion (no HF)',
            'Acid Digestion (no HF)',
            'Borate / Peroxide Fusion ICP',
            'Peroxide Fusion ICP',
            'Aqua Regia Digestion',
            'Aqua Regia Digestion (sample weights 0.15-50g)',
            'Aqua Regia Digestion (sample weights 10-50g)'],

    'Tm': [ '4-Acid Digestion',
            '3-Acid Digestion (no HF)',
            'Acid Digestion (no HF)',
            'Borate / Peroxide Fusion ICP',
            'Peroxide Fusion ICP',
            'Aqua Regia Digestion',
            'Aqua Regia Digestion (sample weights 0.15-50g)',
            'Aqua Regia Digestion (sample weights 10-50g)'],

    'U': [ '4-Acid Digestion',
            '3-Acid Digestion (no HF)',
            'Acid Digestion (no HF)',
            'Borate Fusion XRF',
            'Oxidising Fusion XRF',
            'Pressed Powder Pellet XRF',
            'Borate / Peroxide Fusion ICP',
            'Peroxide Fusion ICP',
            'Aqua Regia Digestion',
            'Aqua Regia Digestion (sample weights 0.15-50g)',
            'Aqua Regia Digestion (sample weights 10-50g)'],

    'V': [ 'Borate Fusion XRF',
            'Oxidising Fusion XRF',
            'Pressed Powder Pellet XRF',
            'Borate / Peroxide Fusion ICP',
            'Peroxide Fusion ICP',
            'Aqua Regia Digestion',
            'Aqua Regia Digestion (sample weights 0.15-50g)',
            'Aqua Regia Digestion (sample weights 10-50g)'],

    'W': [ '4-Acid Digestion',
            '3-Acid Digestion (no HF)',
            'Acid Digestion (no HF)',
            'Borate Fusion XRF',
            'Oxidising Fusion XRF',
            'Pressed Powder Pellet XRF',
            'Borate / Peroxide Fusion ICP',
            'Peroxide Fusion ICP',
            'Aqua Regia Digestion',
            'Aqua Regia Digestion (sample weights 0.15-50g)',
            'Aqua Regia Digestion (sample weights 10-50g)'],

    'Y': [ '4-Acid Digestion',
            '3-Acid Digestion (no HF)',
            'Acid Digestion (no HF)',
            'Borate Fusion XRF',
            'Oxidising Fusion XRF',
            'Pressed Powder Pellet XRF',
            'Borate / Peroxide Fusion ICP',
            'Peroxide Fusion ICP',
            'Aqua Regia Digestion',
            'Aqua Regia Digestion (sample weights 0.15-50g)',
            'Aqua Regia Digestion (sample weights 10-50g)'],

    'Yb': [ '4-Acid Digestion',
            '3-Acid Digestion (no HF)',
            'Acid Digestion (no HF)',
            'Borate / Peroxide Fusion ICP',
            'Peroxide Fusion ICP',
            'Aqua Regia Digestion',
            'Aqua Regia Digestion (sample weights 0.15-50g)',
            'Aqua Regia Digestion (sample weights 10-50g)'],

    'Zn': [ '4-Acid Digestion',
            '3-Acid Digestion (no HF)',
            'Acid Digestion (no HF)',
            'Borate Fusion XRF',
            'Oxidising Fusion XRF',
            'Pressed Powder Pellet XRF',
            'Borate / Peroxide Fusion ICP',
            'Peroxide Fusion ICP',
            'Aqua Regia Digestion',
            'Aqua Regia Digestion (sample weights 0.15-50g)',
            'Aqua Regia Digestion (sample weights 10-50g)'],

    'Zr': [ '4-Acid Digestion',
            '3-Acid Digestion (no HF)',
            'Acid Digestion (no HF)',
            'Borate / Peroxide Fusion ICP',
            'Peroxide Fusion ICP'],

}

# print(analysis_method_prefs_dict['Zn'])

print(list(analysis_method_prefs_dict.keys()))
